sudo: true
language: node_js
node_js:
  - 10.15.1
services:
  - docker
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
  - npm run check
  - docker build -t piotrmoszkowicz/netguru . --no-cache
  - chmod u+x ./scripts/docker_push.sh
  - bash scripts/docker_push.sh
before_deploy:
  - chmod u+x ./scripts/docker_push.sh
deploy:
  - provider: script
    script: bash scripts/docker_push.sh
    skip_cleanup: true
    on:
      branch: master
env:
  global:
    #DOCKER_USERNAME
    - secure: nvrsJa76QUz84ynX2kd93pgqqdm1I2ZUAMKnfy02yexP+7IQxo/2IJhlI9x4w+uGqiH0qTAmMVQq0aSoYhAiTu7+uvbgqUTSz20EBW+w+XVCaHBre6TQ0hfoD6eKPRHFt+ZN7raCUZ+exUxuwNIEWumhaPBaMCRKrQ0sj7gyTzAUB+p1unLBHJDXhFTdJ+D1FbtaOoPk3wlb2Mnox26NFO82R2Y9Edo14vA6DN0uA7sg1cvW9fn2ZazVxwT0jak+6UXINpiUUG14m1Td0Iij8AQlmyXFZ3hHYoyDtdujNE4IsdCZRuP46yRv5gPB27kzxOfk3l+ZkGOcPhCnZwVuxHVUOLIAI64tS/SMkWZ00OcIf9IrsH+QF7zNgII5t40/0UQpEKTclszLntZ0aRA1U3DM6nVquHuxDFmNUaZ29+Wz3vqQR7QPZyBQj/ukzp6FWk/zeB7WNtitmjwTWfBL/uS4mF+4/KUd4ykCEYz4536tNjzMr4nJbvdXCcgAdbBD4fo0isc1pDL99rlxyH490HSwExMNlI6Rn4zLHhWaVvddK764ZGmyMUJPVPyMWunt5W9txM5LbkD2A/WwUWjee1ddWoko5H/8ArUNdxAF1OBQQ/rlpRye9TlvYXdnz7CeB+ap7Nqntfy5WeKwZfRO/uO3hC/MCz0xFyDgO3weA+c=
    #DOCKER_PASSWORD
    - secure: f/2ofxqsGJBBfGHYXiPUKyRszUeMBuR2L1ilair6aznhcjLF2Cz/6Yf6kxcQVnxrxYmuQlfYanb+Ji61WnE8OqY6djDh+M9pe5vSBRAF/+aoXQffpseukLZMNzdPR1DROCiQTD+TPAgULT1R1xRgtmL7YxV2kjYtZkWmRjoEd+dxs22+MdXE2bjsrmcjW1mdKFMVEkIwlwcvm8f9Ejl9EaNbkQ4DSGRjQ5Kl/DZOo7s+8f511wYGaknn6BKPFP2glrJMnTQ72CElvWEeuwAsOmwc+OMMq5QPyhUD6qAqufr6iABCojF1LsAhPjQTfxOnAsHAME0yiWnQpWcl5P8dTbsq3k5ZDDbht80PbtFKZR6184PsyELa59n6wjj7K5Elm40+2PNT1Ql30Bw7PSWSvqyp6L5CX7sK5dDxI3ramlUYNRqSbZqn1tiQ8CTdXQYIQ88nt0hl9CvOJMrXZbjg5Wcsp+UWb/2H3ourFLYs6lBn0IPrKmvhRLCt20zt+L3xN6pc+s+pdZrg7C9j272o8BR+hKc93IjOM8leav6MqV/aHTIfvaQoCqH986BtG+2njC/QSKPeJzYMAIuRyrmCAnE9wGfBupg6WkJnSxAmeNmhoLmLpdvJ0fxnF8BR/h7LCZvu4WhVANoG5rSJBYcciQP9jW3ySWdfG4jMXyFfNq8=