sudo: true
language: node_js
node_js:
- 10.15.1
services:
- docker
branches:
  only:
  - master
install:
- npm install
script:
- npm run build
- npm run check
- docker build -t piotrmoszkowicz/netguru . --no-cache
- chmod u+x ./scripts/docker_push.sh
- bash scripts/docker_push.sh
before_deploy:
- chmod u+x ./scripts/docker_push.sh
deploy:
- provider: script
  script: bash scripts/docker_push.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  #DOCKER_PASSWORD
  - secure: "bJCM5vcl4pNeev3VMQWDai83/7JeYTJmUxMg0dhiRGz1cTkIU/dOX/nX+951e8cftsFObhYOTpt08WWxWF6OTeHkmiGQp8WjdQM6pXF+WrVoMYJTJDZ0R467kWwCE3FCR1fHr+fSCsYTil8oBBio3nNFrXZZJY99G01/MEUGtc39swx52rp1WlaMhdGZoPFNnLfEc+DlbsCGuVxomY1weiQm4sf5sCh6ABbLZ+08kztBSwjYBOmBu21X4/h6WYyke+HOHNBNUlFVS4lu5ypUtU1MoQw+1ZTdrDu6VIFIY6da/xNVZsnT3ouSsDqvzccI548K9PxdeJ/fFbYCuOA9KVvXAL3EvVrscd5QD9GJSlPAjiNXgSyBHPLy7wGwFK1/6GgTBzVbszrDjBnYYesTO+FKvjYwWDCFso0OLQq2Bmr7cLd73hitZxwitUgmqaYbst/qt5EoGXzTLQHo4wkG89kOTq1Vz9MR7sWHEYXbyC4ckLV1+v/JhYuhD+nHWTlJKbUrxs/rcTBzRK9ZCrGyh0UP90TlMJQeGVQnlKhaAvgCC91V/IQplIsAU8jjqel+Ff/L7Pj4fMDX+ePGCZjBWKEh7zaAIvbXrnL6dQEw01Jewr3IPFxcyqTd0cPzdmSmeifMvhSqFGYutcd7mJupwXYlEG2ZDtj9GV6At0QVE64="
  #DOCKER_USERNAME
  - secure: "lbBbmRI8rNvGIcrswd4XNmpgbPU2N37DcckgbZQAV2LxY7hba8S6AXeMSCXStdL0/NeFJgbPhR/ZKwvo/jcAfv490QrYUXIrOiYYUAoaFpkuje8F884XQyms+K2ps/m8O5QArQQ/SFYItwQMMTLnjUGX+yQpOkSQx7jpBc6Ye2fO+xrLH0FpxE/ajbw64ucAvIWRJU9jrRnugD0e2qZ3t3jbQUgJkTmpd4N/sFmqepRt5Mg2nGnKVdA+gp/mOa/rU+FaMq7sQNVcmoQTm1wv3KbevGsXidLEilydQFSzjB9LiScQElB1lzC7HBs7iVHsN+gZqtU5KJoo/Y/ihyUtCc8Z89u6CTAcL/N47W3k4EZHVXRPaon8Lb08m/8N1eOjq3GElQh3il7xE8nakCT+Bic8U5Ldx+hxWoOhsnLLOIQ4ZODnGMsYIiBc3HVYdwpofYNjsPuxroFSE6vD9NAYN14bY5Hp2VzxXkoyrMM+MIjakCPq1DAjWMAyWWeAXoqfC7ZM4UvPqYgFUojgVjvQ2TLcMUZnZUQk2ZpG5IG+P33UQS9oQdZlf310OdV4Zqdyp+zokozIWvhEUa5P9U8qEd+FBwyy6x1ZnWpAsyqkN+Qbzlj5dq8aOh9hKngecCn7ZDmQZv6gr4xWN/nKYQHREM52fe0T+0kMFx36JXuvVsI="
