sudo: true
language: node_js
node_js:
- 10.15.1
services:
- docker
branches:
  only:
  - master
install:
- npm install
script:
- npm run build
- npm run check
- docker build -t piotrmoszkowicz/netguru . --no-cache
- chmod u+x ./scripts/docker_push.sh
- bash scripts/docker_push.sh
before_deploy:
- chmod u+x ./scripts/docker_push.sh
deploy:
- provider: script
  script: bash scripts/docker_push.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  #DOCKER_USERNAME
  - secure: e4tHUsf4VUuPGUgm9bs5pSjfVhLFwvLZq0oGBY3vY8isEj1xcuspohFhT4XUorZOdH465JQrBtJ61dtdN9jICwU69kSU5rz05WiJr25QqRT0lpxSKZLte1ONJqBEBZxvwGk6MD4bMv3c5PQHVD4Oxbi559mMjvGLuCkSyPPzi9AmIczmXSQj+8diYXzRcx9vnustQLjGopphEW3EOqN6/QmS4z6kpzVnNx58NAwR9EGUPQO0y7JtX+vH6OO/bbsp8aK5m+0vogK8l6qfdt3se5m+sUaMS1SNihviKRTU0eujqNNCLnKU1ccEb3EF/CrfsVLuvhFAlBpsRemSJc2KrF91CIyOfJkOzVhpIVGNVT2ruQsIUCL+2RJRjzwZ8DlPNrzGJQUAogh6/FOOXrwcMHGGzUoUF8R1f7S8cNnhr8ERME35GNHwFnBIABBAbXmnzY4h3cjxNXpMbSiwvC7F2ck1zZvKoQtQzhnP30UoObRdWLYB5yr/cC6iedgamCUJ7HKoAqKFCtnENJTSa8M1TcdufkjWwEqysorIdFtZr6uVx9gNGM1eYFDYEM+OaQje2vvaFvv6pYVW4Mu1EuPn7uRWZAfOOeS9uD1Nh1eHEe8J26knkCp0Fav/EJDFTcAhgjtDPqWhG8jToMu8MMTkIZezEFy5/LHjxkEiEfGxA7M=
  #DOCKER_PASSWORD
  - secure: TfdZQpU9uWq8lFQCr153waY+la4esmu8Cea+byDhbFJr5PHR9N9MO3Z8et70Nr8GXKn/YBZ3xES8UUO18qS3kO3jYc2A7ojPjR/tHMO4cf6Ji4XSJLF4a08TdvPwMhxr3RGfRSQ1AcMfq+vxQtUZgavt7gdlnODcnpCka6iB2G5wR83GpSMTs3EOB16oChWeREPbKAY0XjQM8vblr5k3MuZgslZN15joBipZG9SoUg2pG8/VzWELsoAlVdHMu571VAbuP8v6Zaxo32xnIBrL94OyaNDR9qOm7nro2fG32j5oyfKhtBnsMXbPhcsdaX9tTwD4E/A2g+TlaynqRNTj8RhxnVN2g4eeYTJvsteRKXAbhVr4Ja8awMmnxQwJZIwOqrWeK9zF6MIWaEbMbwMS7gdL+Akr8auuIlClA9he8XFTKAQ4EuZo1pUkWt3d1Zvd8oXhaiZ2560mVTKyr8SCQKgppvwViyPBxIH2qCy01l8PermEScKQxYGfQsI12u2wjw5SBr2AD1MCLGE6xoI5aSPcSJaoh6mptyzr+F4i/pMxmlSSqNav3OUENdxGXBjFHSJHImlN5YcHFJFJcJXUtpSvgGXUPpCvK378VwIjWm8i40hUm8otlEsNL32ppJ7BULHJF5T+xAPhL26FsCR5UY2B6me5WrDFBNcejAfycnQ=
