sudo: true
language: node_js
node_js:
- 10.15.1
services:
- docker
branches:
  only:
  - master
install:
- npm install
script:
- npm run build
- npm run check
- docker build -t piotrmoszkowicz/netguru . --no-cache
- chmod u+x ./scripts/docker_push.sh
- bash scripts/docker_push.sh
before_deploy:
- chmod u+x ./scripts/docker_push.sh
deploy:
- provider: script
  script: bash scripts/docker_push.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: k+TjvYHu+YUz0siWVcoELl4q7EJCPekWMj8zq+w8YCw39hX0epQTOjR6mUVG0wT01VnYhvHPi394JiytSsQdmxMLvhF0DKwh4mKAIG10DwSJNdIc5nLoOaQnpHCdVYrdpGkipP4knK8Hq33Cq1U10hStOyD6n7DQkaUiStWf1dObyHEqIRyI5GD6G9praB5UxMLI0oS/5SLygqMw4u7H2IhVT/Q/YAf0qW+tsueoBG7JMg+rFl8q7qiiWb2WmWNf/9Eejq39TTCzfAGvaud8HINdDKQnDVNOboTyoDEE0/Ijb2lbW92asbLiqPpt5hlw4enaXd1tPGaJ6MIRewgEEcOsEgh2QfnCsrJcBnd9FUv8ZM48w55rlPXhT059XSBDDS8fgOUmtWbjdlpTn8hQ60QuujHeNsMZC17P/7QU41BjBtSg/fDt6LlG370NAyFVCgHEdMoLmrPktl8n9VvejSjbLHyUFREAVjU6271RWxBJrc/OdxYPr863Uq2F1iJgK2Y9ntPgMosyNq//N8LQHmr9+koD62GcsPP6Maj9+Wtz+mNCnM/HvZ0y5bT91P/Nap4ml2aFqZB7GWbUrQH34z/FGIRqSPa+YfdRBLV3LBlIJW5kB6NIvBSA1v/ig7MjZxL90GCvKKeTBn4N58kvm1dwiTVjrj4/DjqNU6EtkiY=
  - secure: g+ruQOJoWKk9V9pmoK2oMLZqZLD9dxN2eTZzPNh4sVUho02zZ2VihlUF7JXnNTW9czexX1LY8WPuHKsPPZaiGB5tUzJzTbasB6AWXEovRigLzgcJyJkbrFx3EoZv1cNFe+tkMay/LYLOKTCZS7pcXuxnUEmnV91owm9BdyUMaVn63DVhtLtmk+giZY/hw6AhaeR3kuU7PiHelodx3GVFbjYFsraBMHGWmCzX2KTrYEsp0xLDImztW/KccyKu1Mfar5HlEp5xnmjUucaUflAY1mOZ9nswCmZ2UdPQkNBghKibbOMtFEaPbk8/fHc66KEeZTeeTz8stB/AcupZ0hS2DVT7ZdaklYLDKSKZVpTotuQh5l07Lx82j8UJiNZJ5FLCf48Zc4Eqy7fx9vZg8I5RGN7BL3qITa+aqN1BIeZODdtS3gdW8XgPa74j/ZYaK4dgpchzp+FE04ELbQg2Et8RATYqTU7OK+onY5TZmkw0JBZWr4tEzERE0GapWLI/s65QnK5NbbC9cb07z+PgewiuS4GsMbtYn/J6LX79mkmyfoeTMujLJK7uH11YXVtpoDxpOhphwn6FBWFNIVLamyrHOQbCeGrkpq00J8Z0/mkvTLKNK5/vf+/Fu3o23RcVueMUvCJ5C4yFLA1HGPM2ol1iaJ8Zon9/h2VmRh9xZKlNFpI=
